(self.AMP=self.AMP||[]).push({n:"amp-selector",v:"2010132225003",f:(function(AMP,_){
'use strict';var g,l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function m(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}m(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},r={};try{r.__proto__=q;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n,u;function v(){return u?u:u=Promise.resolve(void 0)};function w(a){return a?Array.prototype.slice.call(a):[]};var x=self.AMP_CONFIG||{},y=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function z(a){if(self.document&&self.document.head&&(!self.location||!y.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}x.cdnUrl||z("runtime-host");x.geoApiUrl||z("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var A=self.__AMP_LOG;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function C(a,b){B().assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function D(a){a=E(a);a=E(a);a=a.isSingleDoc()?a.win:a;return F(a,"action")?G(a,"action"):null}function E(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;b=b.__AMP_TOP||(b.__AMP_TOP=b);a=G(b,"ampdoc").getAmpDoc(a)}return a}function G(a,b){F(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function F(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function H(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function I(a){return a.closest?a.closest("[option]"):H(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"[option]"):!1})}function J(a){return"rtl"==(a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr")};function K(a,b){if(a.length!==b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};var L={NONE:"none",FOCUS:"focus",SELECT:"select"};function M(a){a=AMP.BaseElement.call(this,a)||this;a.l=!1;a.j=[];a.c=[];a.A=[];a.o=null;a.h=0;a.m="none";return a}var N=AMP.BaseElement;M.prototype=l(N.prototype);M.prototype.constructor=M;if(t)t(M,N);else for(var O in N)if("prototype"!=O)if(Object.defineProperties){var P=Object.getOwnPropertyDescriptor(N,O);P&&Object.defineProperty(M,O,P)}else M[O]=N[O];M.H=N.prototype;g=M.prototype;g.isLayoutSupported=function(){return!0};g.prerenderAllowed=function(){return!0};
g.buildCallback=function(){var a=this;this.o=D(this.element);this.l=this.element.hasAttribute("multiple");this.element.hasAttribute("role")||this.element.setAttribute("role","listbox");this.l&&this.element.setAttribute("aria-multiselectable","true");this.element.hasAttribute("disabled")&&this.element.setAttribute("aria-disabled","true");var b=this.element.getAttribute("keyboard-select-mode");b?(b=b.toLowerCase(),B().assertEnumValue(L,b),C(!(this.l&&"select"==b),"[keyboard-select-mode=select] not supported for multiple selection amp-selector")):
b="none";this.m=b;this.registerAction("clear",this.w.bind(this));Q(this);this.element.addEventListener("click",this.B.bind(this));this.element.addEventListener("keydown",this.C.bind(this));this.registerAction("selectUp",function(b){var c=b.args;R(a,c&&void 0!==c.delta?-c.delta:-1,b.trust)},1);this.registerAction("selectDown",function(b){var c=b.args;R(a,c&&void 0!==c.delta?c.delta:1,b.trust)},1);this.registerAction("toggle",function(b){var c=b.args;b=b.trust;C(0<=c.index,"'index' must be greater than 0");
C(c.index<a.c.length,"'index' must be less than the length of options in the <amp-selector>");return c&&void 0!==c.index?S(a,c.index,c.value,b):Promise.reject("'index' must be specified")},1);this.o.addToAllowlist("amp-selector",["clear","selectDown","selectUp","toggle"],["email"]);this.element.addEventListener("amp:dom-update",this.D.bind(this))};
g.mutatedAttributesCallback=function(a){var b=a.selected;void 0!==b&&aa(this,b);var c=a.disabled;void 0!==c&&(c?this.element.setAttribute("aria-disabled","true"):this.element.removeAttribute("aria-disabled"))};
function aa(a,b){var c=Array.isArray(b)?b:[b];if(null===b||0==c.length)a.w();else{a.l||(c=c.slice(0,1));var d=T(a);if(!K(d.sort(),c.sort())){var e=c.reduce(function(a,b){a[b]=!0;return a},Object.create(null));for(b=0;b<a.c.length;b++){c=a.c[b];var f=c.getAttribute("option");e[f]?U(a,c):V(a,c)}W(a);X(a)}}}function W(a,b){if("none"!=a.m){a.c.forEach(function(a){a.tabIndex=-1});var c=b;c||(c=a.l?a.c[0]:a.j[0]||a.c[0]);c&&(a.h=a.c.indexOf(c),c.tabIndex=0)}}
g.D=function(){var a=w(this.element.querySelectorAll("[option]"));K(this.c,a)||Q(this,a)};function Q(a,b){a.j.length=0;var c=b?b:w(a.element.querySelectorAll("[option]"));c.forEach(function(b){b.hasAttribute("role")||b.setAttribute("role","option");b.hasAttribute("disabled")&&b.setAttribute("aria-disabled","true");b.hasAttribute("selected")?U(a,b):V(a,b);b.tabIndex=0});a.c=c;W(a);X(a)}
function X(a){var b=[],c=a.element.getAttribute("name");if(c&&!a.element.hasAttribute("disabled")){var d=a.element.getAttribute("form");a.A.forEach(function(b){a.element.removeChild(b)});a.A=[];var e=a.win.document,f=e.createDocumentFragment();a.j.forEach(function(k){if(!k.hasAttribute("disabled")){var h=e.createElement("input");k=k.getAttribute("option");h.setAttribute("type","hidden");h.setAttribute("name",c);h.setAttribute("value",k);d&&h.setAttribute("form",d);a.A.push(h);f.appendChild(h);b.push(k)}});
a.element.appendChild(f)}}function Y(a,b){b.hasAttribute("disabled")||a.mutateElement(function(){b.hasAttribute("selected")?a.l&&(V(a,b),X(a)):(U(a,b),X(a));W(a,b);Z(a,b,3)})}function T(a){return a.j.map(function(a){return a.getAttribute("option")})}g.B=function(a){!this.element.hasAttribute("disabled")&&(a=a.target)&&(a.hasAttribute("option")||(a=I(a)),a&&Y(this,a))};
function S(a,b,c,d){var e=a.c[b],f=e.hasAttribute("selected"),k=void 0!==c?c:!f,h=a.c.indexOf(a.j[0]);return k===f?v():a.mutateElement(function(){if(h!==b){U(a,e);var c=a.c[h];c&&V(a,c)}else V(a,e);Z(a,e,d)})}
function Z(a,b,c){var d=a.win;b={targetOption:b.getAttribute("option"),selectedOptions:T(a)};var e={detail:b};Object.assign(e,void 0);"function"==typeof d.CustomEvent?d=new d.CustomEvent("amp-selector.select",e):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent("amp-selector.select",!!e.bubbles,!!e.cancelable,b));var f=d;2>c&&B().warn("amp-selector",'"select" event now has the same trust as the originating action. See https://github.com/ampproject/amphtml/issues/24443 for details.');a.o.trigger(a.element,
"select",f,c)}function R(a,b,c){var d=a.c.indexOf(a.j[0]);b=-1===d&&0>b?b:d+b;var e=a.c.length;b=a.c[0<b&&0<e?b%e:(b%e+e)%e];U(a,b);var f=a.c[d];f&&V(a,f);X(a);Z(a,b,c)}g.C=function(a){if(this.element.hasAttribute("disabled"))return v();switch(a.key){case "ArrowLeft":case "ArrowUp":case "ArrowRight":case "ArrowDown":case "Home":case "End":if("none"!=this.m)return ba(this,a);break;case "Enter":case " ":var b=a.key;" "!=b&&"Enter"!=b||!this.c.includes(a.target)||(a.preventDefault(),Y(this,a.target))}return v()};
function ba(a,b){var c=a.win.document,d=0;switch(b.key){case "ArrowLeft":d=J(c)?1:-1;break;case "ArrowUp":d=-1;break;case "ArrowRight":d=J(c)?-1:1;break;case "ArrowDown":d=1;break;case "Home":d=1;break;case "End":d=-1;break;default:return v()}b.preventDefault();a.c[a.h].tabIndex=-1;return ca(a).then(function(c){var e=a.h;switch(b.key){case "Home":a.h=a.c.length-1;break;case "End":a.h=0}do a.h=(a.h+d)%a.c.length,0>a.h&&(a.h+=a.c.length);while(da(a.c[a.h],c[a.h])&&a.h!=e);var k=a.c[a.h];k.tabIndex=
0;try{k.focus()}catch(ea){}var h=a.c[a.h];"select"==a.m&&Y(a,h)})}function V(a,b){b.removeAttribute("selected");b.setAttribute("aria-selected","false");var c=a.j.indexOf(b);-1!==c&&a.j.splice(c,1)}g.w=function(){for(;0<this.j.length;){var a=this.j.pop();V(this,a)}X(this)};function U(a,b){a.j.includes(b)||(a.l||a.w(),b.setAttribute("selected",""),b.setAttribute("aria-selected","true"),a.j.push(b))}g.F=function(){return this.c};g.G=function(){return this.j};
function ca(a){return a.measureElement(function(){return a.c.map(function(a){return a.getBoundingClientRect()})})}function da(a,b){var c=b.width,d=b.height;return a.hidden||0==c||0==d}(function(a){a.registerElement("amp-selector",M,"amp-selector [option]{cursor:pointer}amp-selector [option][selected]{cursor:auto;outline:1px solid rgba(0,0,0,0.7)}amp-selector[multiple] [option][selected]{cursor:pointer;outline:1px solid rgba(0,0,0,0.7)}amp-selector [disabled][option],amp-selector[disabled] [option],amp-selector[disabled] [selected],amp-selector [selected][disabled]{cursor:auto;outline:none}\n/*# sourceURL=/extensions/amp-selector/0.1/amp-selector.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-selector-0.1.js.map
