(self.AMP=self.AMP||[]).push({n:"amp-position-observer",v:"2010132225003",f:(function(AMP,_){
'use strict';var h="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function l(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],d=0;d<b.length;++d){var c=b[d];if(c&&c.Math==Math)return}(function(){throw Error("Cannot find global object");})()}l(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;var t=self.AMP_CONFIG||{},u=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function v(a){if(self.document&&self.document.head&&(!self.location||!u.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}t.cdnUrl||v("runtime-host");t.geoApiUrl||v("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var w=self.__AMP_LOG;function y(){if(!w.user)throw Error("failed to call initLogConstructor");return w.user}function z(a,b,d){return y().assert(a,b,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function A(a){var b=B,d=C(a),c=D(d),e=E(c),g=e["position-observer"];g||(g=e["position-observer"]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});g.ctor||g.obj||(g.ctor=b,g.context=d,g.resolve&&F(c,"position-observer"))}function G(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return F(a,b)}function H(a,b){var d=C(a);d=D(d);return F(d,b)}function aa(a){a=C(a);a=D(a);return I(a,"action")?F(a,"action"):null}
function C(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function D(a){a=C(a);return a.isSingleDoc()?a.win:a}function F(a,b){I(a,b);a=E(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function E(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function I(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function J(a){return a||{}};function K(a,b,d,c){return{left:a,top:b,width:d,height:c,bottom:b+c,right:a+d,x:a,y:b}}function L(a,b){return a.top<b.top?"top":a.bottom>b.bottom?"bottom":"inside"}function M(a,b){return a&&b?a.left==b.left&&a.top==b.top&&a.width==b.width&&a.height==b.height:!1};function N(a,b,d,c){this.element=b;this.P=c;this.fidelity=d;this.turn=0==d?Math.floor(4*Math.random()):0;this.B=null;this.j=H(a,"viewport")}
N.prototype.update=function(a){var b=this;if(!a){if(0!=this.turn){this.turn--;return}0==this.fidelity&&(this.turn=4)}var d=this.j.getSize(),c=K(0,0,d.width,d.height);this.j.getClientRectAsync(this.element).then(function(a){var d={positionRect:a,viewportRect:c,relativePos:null},e=b.B;if(!(e&&M(e.positionRect,d.positionRect)&&M(e.viewportRect,d.viewportRect))){e=d.positionRect;d.relativePos=L(e,d.viewportRect);var k=d.viewportRect;e.top<=k.bottom&&k.top<=e.bottom&&e.left<=k.right&&k.left<=e.right?(b.B=
d,b.P(d)):b.B&&(b.B=null,d.positionRect=null,b.P(d))}})};J({c:!0,v:!0,a:!0,ad:!0});function O(a){z(/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)$/.test(a),"Invalid length value: %s",a);return a};function P(a,b,d){var c={detail:d};Object.assign(c,void 0);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,c);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!c.bubbles,!!c.cancelable,d);return a};function ba(a,b){function d(){c=0;var f=500-(a.Date.now()-e);if(0<f)c=a.setTimeout(d,f);else{var k=g;g=null;b.apply(null,k)}}var c=0,e=0,g=null;return function(b){for(var f=[],x=0;x<arguments.length;++x)f[x-0]=arguments[x];e=a.Date.now();g=f;c||(c=a.setTimeout(d,500))}};function B(a){var b=this;this.V=a;this.U=a.win;this.h=[];this.Z=G(this.U,"vsync");this.j=H(a,"viewport");this.H=[];this.K=this.M=this.L=!1;this.W=ba(this.U,function(){b.L=!1})}B.prototype.observe=function(a,b,d){var c=this,e=new N(this.V,a,b,d);this.h.push(e);this.K||ca(this);e.update();return function(){for(var a=0;a<c.h.length;a++)if(c.h[a]==e){c.h.splice(a,1);0==c.h.length&&Q(c);break}}};
B.prototype.unobserve=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].element==a){this.h.splice(b,1);0==this.h.length&&Q(this);return}if(w.dev)a=w.dev;else throw Error("failed to call initLogConstructor");a.error("POSITION_OBSERVER","cannot unobserve unobserved element")};function ca(a){a.K=!0;a.H.push(a.j.onScroll(function(){a.W();a.L=!0;a.M||R(a)}));a.H.push(a.j.onResize(function(){a.updateAllEntries(!0)}))}function Q(a){for(a.K=!1;a.H.length;)a.H.pop()()}
B.prototype.updateAllEntries=function(a){for(var b=0;b<this.h.length;b++)this.h[b].update(a)};function R(a){a.updateAllEntries();a.M=!0;a.L?a.Z.measure(function(){R(a)}):a.M=!1};function S(a){a=AMP.BaseElement.call(this,a)||this;a.w=null;a.m=null;a.j=null;a.l=!1;a.G=0;a.o=0;a.N="0";a.J="0";a.C=0;a.S=0;a.I=null;a.F=null;a.A=null;a.D=0;a.R=0;a.T=!1;a.O=!1;return a}var T=AMP.BaseElement;S.prototype=h(T.prototype);S.prototype.constructor=S;if(r)r(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.aa=T.prototype;
S.prototype.buildCallback=function(){this.getAmpDoc().whenFirstVisible().then(this.X.bind(this));this.T=this.element.hasAttribute("once")};S.prototype.X=function(){var a=this;da(this);this.w=aa(this.element);this.j=H(this.element,"viewport");this.m||(A(this.getAmpDoc()),this.m=H(this.element,"position-observer"));this.getAmpDoc().whenReady().then(function(){var b=W(a);a.m.observe(b,1,a.Y.bind(a))})};
function X(a){var b=a.j.getScrollTop(),d=J({"start-scroll-offset":b,"end-scroll-offset":b+a.R,"initial-inview-percent":a.D}),c=P(a.win,"amp-position-observer.scroll",J({percent:a.D,positionObserverData:d}));a.w.trigger(a.element,"scroll",c,1)}
S.prototype.Y=function(a){if(!this.T||!this.O){var b=this.l,d=this.I&&this.I.height;this.A||(this.A=a.viewportRect.height);var c=this.A-a.viewportRect.height,e=0;150>Math.abs(c)?e=c:this.A=null;a.viewportRect=K(a.viewportRect.left,a.viewportRect.top,a.viewportRect.width,a.viewportRect.height+e);this.I=a.viewportRect;d!=a.viewportRect.height&&(this.C=Y(this,this.N),this.S=Y(this,this.J));c=a.viewportRect;c=K(c.left,c.top+this.C,c.width,c.height-this.S-this.C);e=a.positionRect;var g;if(e){var f=g=L(e,
c);if("inside"==f)this.l=!0;else{var k=e.height*("top"==f?this.G:this.o);this.l="bottom"==f?e.top<=c.bottom-k:e.bottom>=c.top+k}}else this.l=!1,g=a.relativePos;b&&!this.l&&(this.D="bottom"==g?0:1,X(this),f=P(this.win,"amp-position-observer.exit",J({})),this.w.trigger(this.element,"exit",f,1),this.O=!0);!b&&this.l&&(f=P(this.win,"amp-position-observer.enter",J({})),this.w.trigger(this.element,"enter",f,1));this.l&&(e&&(f=c.height+e.height-(e.height*this.o+e.height*this.G),c=Math.abs(e.top-this.C-(c.height-
e.height*this.o)),this.D=c/f,this.R=f-c),X(this))}};function da(a){var b=a.element.getAttribute("intersection-ratios");if(b){var d=b.trim().split(" ");a.G=Z(d[0]);a.o=a.G;d[1]&&(a.o=Z(d[1]))}var c=a.element.getAttribute("viewport-margins");c&&(c=c.trim().split(" "),a.N=c[0],a.J=a.N,c[1]&&(a.J=c[1]));a.F=a.element.getAttribute("target")}
function W(a){var b=a.F?y().assertElement(a.win.document.getElementById(a.F),"No element found with id:"+a.F):a.element.parentNode;a.win.document.body===b&&(b=a.win.document.documentElement);return b}
function Y(a,b){b="number"==typeof b?b+"px":b&&/^\d+(\.\d+)?(px|em|rem|vh|vw|vmin|vmax|cm|mm|q|in|pc|pt)?$/.test(b)?/^\d+(\.\d+)?$/.test(b)?b+"px":b:void 0;b=O(b);var d=b;O(d);d=z(/[a-z]+/i.exec(d),"Failed to read units from %s",d)[0];var c=parseFloat(b);c="number"===typeof c&&isFinite(c)?c:void 0;if(!c)return 0;z("px"==d||"vh"==d,"Only pixel or vh are valid as units for exclusion margins: "+b);"vh"==d&&(c=c/100*a.I.height);return c}
function Z(a){var b=parseFloat(a);z(0<=b&&1>=b,"Ratios must be a decimal between 0 and 1: "+a);return b}S.prototype.$=function(){if(this.m){var a=W(this);this.m.unobserve(a);this.m=null}};(function(a){a.registerElement("amp-position-observer",S)})(self.AMP);
})});

//# sourceMappingURL=amp-position-observer-0.1.js.map
